import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Network, Plus, RefreshCw, Download, Server, Cpu, ListTodo } from 'lucide-react'
import { useLang } from '../lib/i18n'
import { getConnection } from '../lib/api'
import { distributed, type Cluster, type ClusterHost, type Resources } from '../lib/distributed'
import { PageHead, Field, Empty, Status } from '../components/shared'
import { Button } from '../components/ui/button'
import { Input } from '../components/ui/input'
import { Dialog } from '../components/ui/dialog'
import './distributed.css'

const list=(value:string)=>value.split(',').map(s=>s.trim()).filter(Boolean)
const number=(value:string)=>Math.max(0,Number(value)||0)
const fileDownload=(name:string,content:BlobPart,type='application/json')=>{
  const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a')
  link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
export function Distributed(){
  const lang=useLang(s=>s.lang),zh=lang==='zh',label=(cn:string,en:string)=>zh?cn:en
  const client=useQueryClient(),query=useQuery({queryKey:['distributed'],queryFn:distributed.state,refetchInterval:3000,retry:false})
  const [tab,setTab]=useState('hosts'),[enrolling,setEnrolling]=useState(false),[creating,setCreating]=useState(false)
  const [selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [host,setHost]=useState<ClusterHost|null>(null),[resource,setResource]=useState<Resources>({cpu:1,ram_mb:1024,gpu:0})
  const state=query.data,hosts=Object.values(state?.hosts??{}),instances=Object.values(state?.instances??{}),tasks=Object.values(state?.tasks??{}),artifacts=Object.values(state?.artifacts??{})
  const online=(seen:number,enabled:boolean)=>enabled&&seen>(state?.server_time??Date.now()/1000)-30
  const run=async(action:()=>Promise<unknown>)=>{setError('');setBusy(true);try{await action();await client.invalidateQueries({queryKey:['distributed']})}catch(e){setError(String(e))}finally{setBusy(false)}}
  const task=selected?state?.tasks[selected]:undefined
  return <div className="page distributed-page">
    <PageHead eyebrow="DISTRIBUTED COLLABORATION" title={label('分布式协作','Distributed collaboration')} description={label('Host 提供资源 · AX Instance 提供能力 · AXCrew 统一调度 Execution','Host resources · AX Instance capabilities · AXCrew schedules executions')} actions={<><Button variant="secondary" onClick={()=>void query.refetch()} aria-label={label('刷新集群','Refresh cluster')}><RefreshCw size={14}/></Button><Button variant="secondary" onClick={()=>setEnrolling(true)}><Plus size={14}/>{label('添加 AX 实例','Add AX instance')}</Button><Button onClick={()=>setCreating(true)}><Plus size={14}/>{label('创建协作任务','Create collaboration task')}</Button></>}/>
    {(error||query.error)&&<p role="alert" className="text-danger mb-4">{error||String(query.error)}</p>}
    <div className="cluster-stats">{[[Server,label('在线 Host','Online hosts'),hosts.filter(h=>online(h.last_seen,h.enabled)).length],[Cpu,label('在线 AX','Online AX'),instances.filter(i=>online(i.last_seen,i.enabled)).length],[ListTodo,label('执行中','Running'),tasks.filter(t=>t.status==='running').length],[Network,label('等待调度 / 依赖','Awaiting placement / dependencies'),tasks.filter(t=>t.status==='pending').length]].map(([Icon,title,count])=>{const I=Icon as typeof Server;return <div className="panel cluster-stat" key={String(title)}><I size={20}/><span>{String(title)}</span><strong>{String(count)}</strong></div>})}</div>
    <div className="cluster-tabs" role="tablist" aria-label={label('集群管理','Cluster management')}>{[['hosts','Host','Hosts'],['instances','AX 实例','AX instances'],['workflows','工作流','Workflows'],['tasks','协作任务','Tasks'],['artifacts','产物','Artifacts'],['events','观测与事件','Observations & events']].map(([id,cn,en])=><button key={id} type="button" role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label(cn,en)}</button>)}</div>
    {query.isPending?<Empty title={label('正在读取集群状态…','Loading cluster state…')}/>:!hosts.length?<div className="panel cluster-intro"><Network size={36}/><h2>{label('连接你的第一个 AX','Connect your first AX')}</h2><p>{label('添加 Host 和 AX 实例，下载 worker 配置，在对应机器设置本地项目路径并运行 ax crew worker。一个 Host 可添加多个不同职责的 AX，每个 AX 可并发执行多个任务。','Add a Host and AX instance, download the worker config, map logical projects to local paths, and run ax crew worker on that machine. Each Host supports multiple AX instances and each AX supports concurrent executions.')}</p><Button onClick={()=>setEnrolling(true)}>{label('添加 AX 实例','Add AX instance')}</Button></div>:null}
    {tab==='hosts'&&hosts.map(h=>{const current=tasks.filter(t=>t.status==='running'&&instances.find(i=>i.id===t.owner)?.host_id===h.id),used=current.reduce((r,t)=>({cpu:r.cpu+t.spec.requirements.resources.cpu,ram_mb:r.ram_mb+t.spec.requirements.resources.ram_mb,gpu:r.gpu+t.spec.requirements.resources.gpu}),{cpu:0,ram_mb:0,gpu:0});return <section className="panel cluster-card" key={h.id}><div className="cluster-card-head"><Server size={18}/><strong>{h.name}</strong><Status value={!h.enabled?'disabled':online(h.last_seen,h.enabled)?'online':'offline'}/><Button disabled={busy} variant="ghost" onClick={()=>void run(()=>distributed.enable('hosts',h.id,!h.enabled))}>{h.enabled?label('禁用','Disable'):label('启用','Enable')}</Button><Button variant="secondary" onClick={()=>{setHost(h);setResource(h.resources)}}>{label('资源配置','Configure resources')}</Button></div><p className="tiny mono">{h.id}</p><p className="text-sm text-muted">CPU {used.cpu}/{h.resources.cpu} · RAM {used.ram_mb}/{h.resources.ram_mb} MiB · GPU {used.gpu}/{h.resources.gpu}</p><div className="cluster-instance-list">{instances.filter(i=>i.host_id===h.id).map(i=><div key={i.id}><Cpu size={14}/><b>{i.name}</b><span>{i.capabilities.roles.join(', ')}</span><span>{tasks.filter(t=>t.owner===i.id&&t.status==='running').length}/{i.max_executions} Execution</span><Status value={!i.enabled?'disabled':online(i.last_seen,i.enabled)?'online':'offline'}/></div>)}</div></section>})}
    {tab==='instances'&&instances.map(i=><section className="panel cluster-card" key={i.id}><div className="cluster-card-head"><Cpu size={18}/><strong>{i.name}</strong><Status value={!i.enabled?'disabled':online(i.last_seen,i.enabled)?'online':'offline'}/><Button disabled={busy} variant="ghost" onClick={()=>void run(()=>distributed.enable('instances',i.id,!i.enabled))}>{i.enabled?label('禁用','Disable'):label('启用','Enable')}</Button></div><p className="tiny mono">{i.id} · Host {i.host_id}</p><div className="cluster-capabilities">{Object.entries(i.capabilities).map(([key,values])=><div key={key}><span>{key}</span><b>{values.join(', ')||'—'}</b></div>)}<div><span>{label('逻辑项目','Logical projects')}</span><b>{i.projects.join(', ')}</b></div><div><span>{label('并发 / 自主委派','Concurrency / delegation')}</span><b>{i.max_executions} / {i.can_delegate?label('允许','Allowed'):label('禁止','Denied')}</b></div></div></section>)}
    {tab==='tasks'&&<div className="panel">{!tasks.length&&<Empty title={label('还没有协作任务','No collaboration tasks yet')}/>} {tasks.slice().reverse().map(t=><button className="row cluster-task-row" key={t.id} onClick={()=>setSelected(t.id)}><ListTodo size={15}/><span className="cluster-task-title"><b>{t.spec.title}</b><small>{t.spec.project_id} · {t.owner?instances.find(i=>i.id===t.owner)?.name??t.owner:label('等待能力 / 资源 / 依赖','Waiting for capabilities / resources / dependencies')} · #{t.generation}</small></span><Status value={t.status}/></button>)}</div>}
    {tab==='artifacts'&&<div className="panel">{!artifacts.length&&<Empty title={label('还没有协作产物','No collaboration artifacts yet')}/>} {artifacts.map(a=><div className="row" key={a.id}><span className="cluster-task-title"><b>{a.name}</b><small>{a.kind} · {a.project_id} · {a.size} bytes · #{a.generation}</small><small className="mono">SHA256 {a.sha256}</small></span><Button disabled={busy} variant="ghost" aria-label={`${label('下载','Download')} ${a.name}`} onClick={()=>void run(async()=>{const value=await distributed.artifact(a.id);fileDownload(a.name,Uint8Array.from(atob(value.content_base64),c=>c.charCodeAt(0)),'application/octet-stream')})}><Download size={16}/></Button></div>)}</div>}
    {tab==='events'&&<div className="panel">{!(state?.events.length)&&<Empty title={label('还没有集群事件','No cluster events yet')}/>} {state?.events.slice(-200).reverse().map(e=><div className="cluster-event" key={e.sequence}><span className="tiny mono">#{e.sequence} · {new Date(e.timestamp*1000).toLocaleString()} · {e.kind}</span>{e.task_id&&<button onClick={()=>setSelected(e.task_id)} className="text-accent tiny mono">{e.task_id}</button>}<pre>{e.detail}</pre></div>)}</div>}
    <Dialog open={!!task} onOpenChange={open=>{if(!open)setSelected(null)}} title={task?.spec.title??''}>{task&&<div className="cluster-detail">{error&&<p role="alert" className="text-danger">{error}</p>}<Status value={task.status}/><p className="tiny mono">{task.id} · {task.spec.project_id}</p><p>{label('执行者','Owner')}: {task.owner??'—'} · {label('代次','Generation')}: {task.generation}</p><p>{label('父任务','Parent')}: {task.spec.parent_id??'—'}</p><p>{label('依赖','Dependencies')}: {task.spec.dependencies.join(', ')||'—'}</p><pre>{task.spec.input}</pre><pre>{JSON.stringify(task.spec.requirements,null,2)}</pre><h3>{label('结果 / 错误','Result / failure')}</h3><pre>{task.result??task.failure??label('等待结果','Awaiting result')}</pre><h3>{label('执行记录','Attempts')}</h3>{task.attempts.map(a=><p key={a.generation}>#{a.generation} · {a.instance_id} · {a.error??'—'}</p>)}<h3>{label('Observation','Observations')}</h3>{state?.events.filter(e=>e.task_id===task.id&&e.kind==='task.observation').map(e=><pre key={e.sequence}>{e.detail}</pre>)}<div className="flex gap-2">{['pending','running'].includes(task.status)&&<Button disabled={busy} variant="danger" onClick={()=>void run(()=>distributed.control(task.id,'cancel'))}>{label('取消任务及子任务','Cancel task and descendants')}</Button>}{task.status==='failed'&&<Button disabled={busy} onClick={()=>void run(()=>distributed.control(task.id,'retry'))}>{label('重试','Retry')}</Button>}</div></div>}</Dialog>
    {tab==='workflows'&&<>{!Object.keys(state?.workflows??{}).length&&<Empty title={label('还没有持久化工作流','No durable workflows yet')}/>} {Object.values(state?.workflows??{}).map(w=><section className="panel cluster-card cluster-detail" key={w.id}><div className="cluster-card-head"><Network size={18}/><strong>{w.title}</strong><Status value={w.status}/></div><p className="tiny mono">{w.id} · {w.project_id} · revision {w.revision}</p><p className="text-muted">{label('任务、事件和检查点由 AXCrew 保存，Coordinator AX 离线不会删除工作流。','AXCrew retains tasks, events and checkpoints independently of coordinator availability.')}</p><pre>{JSON.stringify(w.state,null,2)}</pre><Button variant="secondary" onClick={()=>setSelected(w.root_task_id)}>{label('查看根任务 / 取消 / 恢复','Root task / cancel / recover')}</Button></section>)}</>}
    <Dialog open={!!host} onOpenChange={open=>{if(!open)setHost(null)}} title={label('Host 资源','Host resources')}>{error&&<p role="alert" className="text-danger mb-4">{error}</p>}<p className="text-sm text-muted mb-4">{label('容量属于 Host，同一机器上的 AX 共用资源预留。','Capacity belongs to the Host; AX instances on this machine share reservations.')}</p>{(['cpu','ram_mb','gpu'] as const).map(key=><Field key={key} label={key==='ram_mb'?'RAM (MiB)':key.toUpperCase()}><Input type="number" min={key==='cpu'?1:0} value={resource[key]} onChange={e=>setResource({...resource,[key]:number(e.target.value)})}/></Field>)}<Button disabled={busy||resource.cpu<1} onClick={()=>void run(async()=>{await distributed.resources(host!.id,resource);setHost(null)})}>{label('保存','Save')}</Button></Dialog>
    <Enroll open={enrolling} close={()=>setEnrolling(false)} state={state} run={run} busy={busy} label={label} error={error}/>
    <CreateTask open={creating} close={()=>setCreating(false)} state={state} run={run} busy={busy} label={label} error={error}/>
  </div>
}
type FormProps={open:boolean;close:()=>void;state?:Cluster;run:(action:()=>Promise<unknown>)=>Promise<void>;busy:boolean;error:string;label:(cn:string,en:string)=>string}
function Enroll({open,close,state,run,busy,label,error}:FormProps){
  const [form,setForm]=useState({host_id:'',host_name:'',name:'AX-code',cpu:'4',ram:'8192',gpu:'0',project:'project-ax',path:'',roles:'code',skills:'',mcp:'',tools:'shell, filesystem, patch, search',model:'',provider:'',environment:'',concurrency:'2',gateway:'',permission:'ask',delegate:true})
  const [config,setConfig]=useState<Record<string,unknown>|null>(null)
  const field=(key:keyof typeof form,cn:string,en:string,placeholder='')=><Field label={label(cn,en)}><Input value={String(form[key])} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>
  const existing=state?.hosts[form.host_id]
  return <Dialog open={open} onOpenChange={value=>{if(!value){setConfig(null);close()}}} title={label('添加 AX 实例','Add AX instance')}>{error&&<p role="alert" className="text-danger mb-4">{error}</p>}{config?<><p className="mb-4 text-sm text-muted">{label('保存配置到目标机器，核对本地路径、AX_HOME、模型和权限后运行。配置包含该实例的私有凭证。','Save this config on the target machine. Check local paths, AX_HOME, model and permissions, then run. It contains this instance’s private credential.')}</p><pre className="cluster-config">{JSON.stringify(config,null,2)}</pre><pre className="cluster-config">ax crew worker worker.json</pre><Button onClick={()=>fileDownload('worker.json',JSON.stringify(config,null,2))}><Download size={14}/>{label('下载 worker 配置','Download worker config')}</Button></>:<div className="cluster-form"><p className="text-sm text-muted">{label('同一台机器的实例请使用相同 Host ID。Worker 会主动连接 AXCrew，不要求机器开放入站端口。','Instances on the same machine must use the same Host ID. Workers connect outbound to AXCrew; no inbound port is needed.')}</p><div className="cluster-form-grid">{field('host_id','Host ID','Host ID','build-server-01')}{field('host_name','机器名称','Host name')}{field('name','AX 名称','AX name')}{field('project','逻辑项目 ID','Logical project ID')}{field('path','此机器上的项目路径','Local project path','D:\\AX or /srv/AX')}{field('gateway','AXCrew 地址（远程使用 HTTPS）','AXCrew URL (HTTPS for remote)','https://crew.example.com')}</div>
      {!existing?<div className="cluster-form-grid">{field('cpu','CPU 核数','CPU cores')}{field('ram','RAM（MiB）','RAM (MiB)')}{field('gpu','GPU 数量','GPU count')}</div>:<p className="tiny">{label('使用已有 Host 容量','Using existing Host capacity')}: CPU {existing.resources.cpu} · RAM {existing.resources.ram_mb} · GPU {existing.resources.gpu}</p>}
      <div className="cluster-form-grid">{field('roles','角色（逗号分隔）','Roles (comma separated)')}{field('concurrency','并发 Execution 数','Concurrent executions')}{field('model','模型 ID','Model ID')}{field('provider','Provider ID','Provider ID')}{field('skills','Skill 名称','Skill names')}{field('mcp','MCP 名称','MCP names')}{field('tools','Tool 名称','Tool names')}{field('environment','环境标签','Environment tags')}<Field label={label('预先授权的执行权限','Preauthorized execution permissions')}><select value={form.permission} onChange={e=>setForm({...form,permission:e.target.value})}><option value="ask">{label('Ask（无人值守时拒绝待授权操作）','Ask (unattended requests are denied)')}</option><option value="allow">{label('Allow（使用本机 Sandbox / Policy）','Allow (local sandbox / policy applies)')}</option><option value="deny">Deny</option></select></Field><label className="cluster-check"><input type="checkbox" checked={form.delegate} onChange={e=>setForm({...form,delegate:e.target.checked})}/>{label('允许 AX 自主委派','Allow AX delegation')}</label></div>
      <Button disabled={busy||!form.host_id||!form.name||!form.project||!form.path||number(form.concurrency)<1} onClick={()=>void run(async()=>{
        const connection=await getConnection();const result=await distributed.enroll({host_id:form.host_id,host_name:form.host_name||form.host_id,name:form.name,resources:existing?.resources??{cpu:number(form.cpu),ram_mb:number(form.ram),gpu:number(form.gpu)},projects:[form.project],max_executions:number(form.concurrency),can_delegate:form.delegate,capabilities:{roles:list(form.roles),skills:list(form.skills),mcp:list(form.mcp),tools:list(form.tools),models:list(form.model),permissions:[form.permission],environments:list(form.environment)}})
        setConfig({gateway:form.gateway||connection.endpoint,instance_id:result.instance.id,token:result.token,projects:{[form.project]:form.path},execution_root:'./executions/'+result.instance.id,ax_home:'./ax-home/'+result.instance.id,max_executions:number(form.concurrency),...(form.model?{model:form.model}:{}),...(form.provider?{provider:form.provider}:{}),skills:list(form.skills),mcp:list(form.mcp),permission_profile:form.permission,sandbox:'strict'})
      })}>{label('注册并生成配置','Register and generate config')}</Button></div>}</Dialog>
}
function CreateTask({open,close,state,run,busy,label,error}:FormProps){
  const [form,setForm]=useState({title:'',input:'',project:'',role:'',cpu:'1',ram:'0',gpu:'0',dependencies:'',artifacts:'',revision:'',summary:'',requirements:'{}'})
  const field=(key:keyof typeof form,cn:string,en:string)=><Field label={label(cn,en)}><Input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>
  const projects=[...new Set(Object.values(state?.instances??{}).flatMap(i=>i.projects))]
  return <Dialog open={open} onOpenChange={value=>{if(!value)close()}} title={label('创建协作任务','Create collaboration task')}>{error&&<p role="alert" className="text-danger mb-4">{error}</p>}<div className="cluster-form">{field('title','任务标题','Task title')}<Field label={label('任务输入','Task input')}><textarea rows={4} value={form.input} onChange={e=>setForm({...form,input:e.target.value})}/></Field><div className="cluster-form-grid"><Field label={label('逻辑项目','Logical project')}><select value={form.project||projects[0]||''} onChange={e=>setForm({...form,project:e.target.value})}>{projects.map(p=><option key={p}>{p}</option>)}</select></Field>{field('role','需要的角色','Required role')}{field('cpu','CPU','CPU')}{field('ram','RAM（MiB）','RAM (MiB)')}{field('gpu','GPU','GPU')}{field('revision','Git commit（可选）','Git commit (optional)')}{field('dependencies','依赖任务 ID（逗号分隔）','Dependency task IDs (comma separated)')}{field('artifacts','Artifact ID（逗号分隔）','Artifact IDs (comma separated)')}</div>{field('summary','必要 Context Summary','Necessary context summary')}<Field label={label('额外能力要求（JSON：skills / mcp / tools / models / permissions / environments）','Additional capability requirements (JSON: skills / mcp / tools / models / permissions / environments)')}><textarea rows={3} value={form.requirements} onChange={e=>setForm({...form,requirements:e.target.value})}/></Field><Button disabled={busy||!form.title.trim()||!form.input.trim()||!projects.length} onClick={()=>void run(async()=>{await distributed.submit({request_id:crypto.randomUUID(),title:form.title,input:form.input,project_id:form.project||projects[0],context_summary:form.summary,workspace_revision:form.revision||null,dependencies:list(form.dependencies),artifacts:list(form.artifacts),requirements:{capabilities:{...JSON.parse(form.requirements),...(form.role?{roles:list(form.role)}:{})},resources:{cpu:number(form.cpu),ram_mb:number(form.ram),gpu:number(form.gpu)}}});setForm({...form,title:'',input:''});close()})}>{label('交由 AXCrew 调度','Schedule through AXCrew')}</Button></div></Dialog>
}
