import { translate, useLang } from '../lib/i18n'
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowRight, Plus, Play, Pencil, Trash2 } from 'lucide-react'
import { Virtuoso } from 'react-virtuoso'
import { Action, Empty, Field, PageHead, Select, Status } from '../components/shared'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Input, Textarea } from '../components/ui/input'
import { api } from '../lib/api'
import { useAllMembers, useCrews, useTasks } from '../lib/query'
import type { Task } from '../lib/types'
import { short,time } from '../lib/utils'
import { SessionThread } from './Sessions'
import { MessageMarkdown } from '../components/MessageMarkdown'

type Draft={crew_id:string;title:string;description:string;assigned_member:string;parent_id:string|null;dependencies:string[];priority:number;input:{prompt:string;include_dependencies:boolean}}
function promptOf(task:Task){return typeof task.input==='string'?task.input:typeof task.input==='object'&&task.input&&'prompt' in task.input?String(task.input.prompt):JSON.stringify(task.input)}
function TaskEditor({task,crewId,close}:{task?:Task;crewId?:string;close:()=>void}){
  useLang(state=>state.lang);

  const crews=useCrews(),members=useAllMembers(),tasks=useTasks(),[form,setForm]=useState<Draft>({crew_id:task?.crew_id??crewId??'',title:task?.title??'',description:task?.description??'',assigned_member:task?.assigned_member??'',parent_id:task?.parent_id??null,dependencies:task?.dependencies??[],priority:task?.priority??0,input:{prompt:task?promptOf(task):'',include_dependencies:!!(task?.input&&typeof task.input==='object'&&'include_dependencies' in task.input&&task.input.include_dependencies)}})
  useEffect(()=>{if(!form.crew_id&&crews.data?.[0])setForm(f=>({...f,crew_id:crews.data![0].id}))},[crews.data,form.crew_id])
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setForm(f=>({...f,[key]:value}))
  const available=(tasks.data??[]).filter(t=>t.crew_id===form.crew_id&&t.id!==task?.id)
  const assignments=(members.data??[]).filter(m=>m.crew_id===form.crew_id)
  return <div className="stack"><div className="form-grid"><Field label={translate("english.110")}><Select value={form.crew_id} disabled={!!task} onChange={v=>setForm(f=>({...f,crew_id:v,assigned_member:'',dependencies:[],parent_id:null}))}>{crews.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label={translate("english.111")}><Select value={form.assigned_member} onChange={v=>set('assigned_member',v)}><option value="">{translate("english.112")}</option>{assignments.map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</Select></Field></div>
    <Field label={translate("english.113")}><Input value={form.title} onChange={e=>set('title',e.target.value)}/></Field><Field label={translate("english.114")}><Input value={form.description} onChange={e=>set('description',e.target.value)}/></Field><Field label={translate("english.115")}><Textarea value={form.input.prompt} onChange={e=>set('input',{...form.input,prompt:e.target.value})} rows={6}/></Field>
    <div className="form-grid"><Field label={translate("english.116")}><Select value={form.parent_id??''} onChange={v=>set('parent_id',v||null)}><option value="">{translate("english.117")}</option>{available.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</Select></Field><Field label={translate("english.118")}><Input type="number" value={form.priority} onChange={e=>set('priority',Number(e.target.value))}/></Field></div>
    <Field label={translate("english.119")} hint={translate("english.120")}><div className="max-h-36 overflow-y-auto rounded-[var(--radius-chip)] border border-border p-2">{available.map(t=><label key={t.id} className="flex items-center gap-2 py-1 text-xs text-foreground"><input type="checkbox" checked={form.dependencies.includes(t.id)} onChange={e=>set('dependencies',e.target.checked?[...form.dependencies,t.id]:form.dependencies.filter(id=>id!==t.id))}/><span className="flex-1 truncate">{t.title}</span><Status value={t.status}/></label>)}{!available.length&&<span className="text-xs text-muted">{translate("english.121")}</span>}</div></Field>
    <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.input.include_dependencies} onChange={e=>set('input',{...form.input,include_dependencies:e.target.checked})}/> {translate("english.122")}</label>
    <div className="flex justify-end"><Action disabled={!form.crew_id||!form.assigned_member||!form.title.trim()||!form.input.prompt.trim()} run={async()=>{const body={...form,input:form.input.include_dependencies?form.input:form.input.prompt};await api(task?`/api/tasks/${task.id}`:'/api/tasks',task?'PUT':'POST',task?{...body,crew_id:undefined}:body);close()}}>{task?translate('detail.4'):translate('detail.5')}</Action></div></div>
}
function Dag({tasks}:{tasks:Task[]}){
  useLang(state=>state.lang);

  const {nodes,width,height,edges}=useMemo(()=>{
    const depth=new Map<string,number>();const visit=(t:Task,seen=new Set<string>()):number=>{if(depth.has(t.id))return depth.get(t.id)!;if(seen.has(t.id))return 0;seen.add(t.id);const value=Math.max(0,...t.dependencies.map(id=>{const dep=tasks.find(x=>x.id===id);return dep?visit(dep,new Set(seen))+1:0}));depth.set(t.id,value);return value};tasks.forEach(t=>visit(t));
    const counts=new Map<number,number>();const nodes=tasks.map(t=>{const x=depth.get(t.id)??0,y=counts.get(x)??0;counts.set(x,y+1);return {task:t,x,y}});const map=new Map(nodes.map(n=>[n.task.id,n]));const edges=nodes.flatMap(n=>n.task.dependencies.map(dep=>({a:map.get(dep),b:n})).filter((e):e is {a:typeof n;b:typeof n}=>!!e.a));return {nodes,edges,width:(Math.max(0,...nodes.map(n=>n.x))+1)*260+20,height:Math.max(200,(Math.max(0,...nodes.map(n=>n.y))+1)*100+20)}
  },[tasks]);if(!tasks.length)return <Empty title={translate("english.123")}/>
  return <div className="relative overflow-auto rounded-[var(--radius-card)] border border-border" style={{height:Math.min(height+25,520)}}><div className="relative" style={{width,height}}><svg className="absolute inset-0 pointer-events-none" width={width} height={height}>{edges.map(({a,b},i)=><path key={i} d={`M ${a.x*260+235} ${a.y*100+47} C ${a.x*260+254} ${a.y*100+47}, ${b.x*260-2} ${b.y*100+47}, ${b.x*260+12} ${b.y*100+47}`} fill="none" stroke="var(--color-muted)" strokeWidth="1.5"/>)}</svg>{nodes.map(({task:t,x,y})=><Link key={t.id} to={`/tasks/${t.id}`} className="dag-node absolute no-underline text-foreground" style={{left:x*260+12,top:y*100+10}}><div className="mb-2 truncate text-[13px] font-medium">{t.title}</div><div className="flex justify-between"><Status value={t.status}/><span className="tiny mono">{short(t.id)}</span></div></Link>)}</div></div>
}
export function Tasks(){
  useLang(state=>state.lang);
const tasks=useTasks(),crews=useCrews(),[params,setParams]=useSearchParams(),crewId=params.get('crew')??'',status=params.get('status')??'', [editing,setEditing]=useState(false)
  const scoped=(tasks.data??[]).filter(t=>!crewId||t.crew_id===crewId),filtered=scoped.filter(t=>!status||t.status===status)
  return <div className="page"><PageHead eyebrow={translate("english.124")} title={translate("english.125")} description={translate("english.126")} actions={<Button onClick={()=>{const next=new URLSearchParams(params);next.set('create','1');setParams(next)}}><Plus size={14}/> {translate("english.127")}</Button>}/><div className="mb-4 flex flex-wrap items-center gap-3"><div className="w-56"><Select value={crewId} onChange={v=>{const next=new URLSearchParams(params);if(v)next.set('crew',v);else next.delete('crew');setParams(next)}}><option value="">{translate("english.3")}</option>{crews.data?.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select></div><div className="w-52"><Select value={status} onChange={v=>{const next=new URLSearchParams(params);next.set('status',v);setParams(next)}}><option value="">{translate("english.128")}</option>{['pending','ready','running','waiting_permission','waiting_user','completed','failed','cancelled'].map(s=><option key={s} value={s}>{translate('status.'+s)}</option>)}</Select></div>{crewId&&<Action run={async()=>{for(const t of scoped.filter(t=>t.status==='pending'&&!t.dependencies.length))await api(`/api/tasks/${t.id}/start`,'POST',{})}} disabled={!scoped.some(t=>t.status==='pending'&&!t.dependencies.length)}><Play size={13}/> {translate("english.129")}</Action>}</div>
    {crewId&&<><h2 className="section-title">{translate("english.130")}</h2><Dag tasks={scoped}/></>}
    <h2 className="section-title">{translate("english.131")}{filtered.length}</h2><div className="panel" style={{height:Math.min(550,Math.max(150,filtered.length*66))}}>{filtered.length?<Virtuoso data={filtered} itemContent={(_,t)=><Link key={t.id} to={`/tasks/${t.id}`} className="row no-underline text-foreground"><Status value={t.status}/><div className="min-w-0 flex-1"><div className="row-title truncate">{t.title}</div><div className="row-sub">{crews.data?.find(c=>c.id===t.crew_id)?.name} · {t.dependencies.length} {translate("english.132")}</div></div><ArrowRight size={14} className="text-muted"/></Link>}/>:<Empty title={translate("english.133")}/>}</div>
    <Dialog open={params.get('create')==='1'||editing} onOpenChange={v=>{if(!v){setEditing(false);const next=new URLSearchParams(params);next.delete('create');setParams(next)}}} title={translate("english.98")} wide><TaskEditor crewId={crewId} close={()=>{setEditing(false);const next=new URLSearchParams(params);next.delete('create');setParams(next)}}/></Dialog>
  </div>
}
export function TaskDetail(){
  useLang(state=>state.lang);
const {id=''}=useParams(),navigate=useNavigate(),tasks=useTasks(),crews=useCrews(),members=useAllMembers(),[edit,setEdit]=useState(false),task=tasks.data?.find(t=>t.id===id)
  if(!task)return <div className="page"><Empty title={tasks.isPending?translate("copy.142"):tasks.isError?translate("copy.143"):translate("copy.144")}/></div>
  const canEdit=['pending','failed','cancelled'].includes(task.status),canStart=task.status==='pending'&&task.dependencies.every(dep=>tasks.data?.find(t=>t.id===dep)?.status==='completed')
  return <div className="page"><PageHead eyebrow={translate("english.134")} title={task.title} description={`${crews.data?.find(c=>c.id===task.crew_id)?.name??''} · ${members.data?.find(m=>m.id===task.assigned_member)?.name??short(task.assigned_member)}`} actions={<><Status value={task.status}/>{canStart&&<Action variant="default" run={()=>api(`/api/tasks/${id}/start`,'POST',{})}><Play size={13}/> {translate("english.135")}</Action>}{['running','ready','waiting_permission','pending'].includes(task.status)&&<Action variant="danger" run={()=>api(`/api/tasks/${id}/cancel`,'POST',{})}>{translate("english.136")}</Action>}{['failed','cancelled'].includes(task.status)&&<Action run={()=>api(`/api/tasks/${id}/retry`,'POST',{})}>{translate("english.137")}</Action>}{canEdit&&<Button variant="secondary" onClick={()=>setEdit(true)}><Pencil size={13}/> {translate("english.138")}</Button>}{!['running','ready','waiting_permission','waiting_user'].includes(task.status)&&<Action variant="danger" run={async()=>{if(window.confirm(`Delete ${task.title}?`)){await api(`/api/tasks/${id}`,'DELETE');navigate('/tasks',{replace:true})}}}><Trash2 size={13}/> {translate("english.139")}</Action>}</>}/>
    <div className="grid gap-5 xl:grid-cols-[1fr_340px]"><div><div className="panel"><div className="panel-header">{translate("english.140")}</div><pre className="whitespace-pre-wrap break-words p-4 text-[13px]">{promptOf(task)}</pre></div><h2 className="section-title">{translate("english.141")}</h2><div className="panel min-h-80"><SessionThread taskId={id}/></div></div><aside><div className="panel"><div className="panel-header">{translate("english.142")}</div><div className="space-y-3 p-4 text-xs"><div><span className="text-muted">{translate("english.11")}</span><div>{task.assigned_device}</div></div><div><span className="text-muted">{translate("english.143")}</span><div>{time(task.created_at)}</div></div><div><span className="text-muted">{translate("english.144")}</span><div>{time(task.started_at)} / {time(task.finished_at)}</div></div><div><span className="text-muted">{translate("english.145")}</span><div>{task.retry_count+1}</div></div><div><span className="text-muted">{translate("english.119")}</span><div className="space-y-1">{task.dependencies.map(dep=><div key={dep}><Link className="link" to={`/tasks/${dep}`}>{tasks.data?.find(t=>t.id===dep)?.title??short(dep)}</Link></div>)}{!task.dependencies.length&&translate('detail.7')}</div></div>{task.output&&<div><span className="text-muted">{translate("english.146")}</span>{task.output.text?<div className="mt-1"><MessageMarkdown text={task.output.text}/></div>:<pre className="mt-1 max-h-52 overflow-auto whitespace-pre-wrap break-all">{task.output.error}</pre>}</div>}</div></div></aside></div>
    <Dialog open={edit} onOpenChange={setEdit} title={translate("english.147")} wide><TaskEditor key={id} task={task} close={()=>setEdit(false)}/></Dialog>
  </div>
}
