import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Plus, Settings2 } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { Action, Empty, Field, PageHead, Select, Status } from '../components/shared'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Input } from '../components/ui/input'
import { useDebouncedValue } from '../lib/useDebouncedValue'
import { api, endpoints } from '../lib/api'
import { useCrews, useDevices, useMembers, useTasks } from '../lib/query'
import type { Member } from '../lib/types'
import { SessionThread } from './Sessions'

const blank=(cwd:string,device='local'):Omit<Member,'id'|'crew_id'>=>({name:'',role:'',device_id:device,cwd,provider:null,model:null,skills:[],mcp_servers:[],permission_profile:'ask',max_concurrency:1})
export function Crews(){const crews=useCrews(),tasks=useTasks(),[params,setParams]=useSearchParams(),[name,setName]=useState(''),open=params.get('create')==='1'
  return <div className="page"><PageHead eyebrow="Workspaces" title="Crews" description="Persistent groups of AX agents across devices" actions={<Button onClick={()=>setParams({create:'1'})}><Plus size={14}/> Create Crew</Button>}/><div className="panel">{crews.data?.map(c=><Link key={c.id} to={`/crews/${c.id}`} className="row no-underline text-foreground"><div className="min-w-0 flex-1"><div className="row-title">{c.name}</div><div className="row-sub">{tasks.data?.filter(t=>t.crew_id===c.id&&['running','waiting_permission'].includes(t.status)).length??0} active tasks</div></div><ArrowUpRight size={15} className="text-muted"/></Link>)}{!crews.data?.length&&<Empty title="No Crews yet" description="Create a Crew to organize AX members, sessions and tasks."/>}</div><Dialog open={open} onOpenChange={value=>!value&&setParams({})} title="Create Crew"><Field label="Crew name"><Input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Dev Crew"/></Field><div className="mt-5"><Action disabled={!name.trim()} run={async()=>{await api('/api/crews','POST',{name});setName('');setParams({})}}>Create Crew</Action></div></Dialog></div>}

function MemberEditor({crewId,member,close}:{crewId:string;member?:Member;close:()=>void}){
  const devices=useDevices(),settings=useQuery({queryKey:['settings'],queryFn:endpoints.settings}),[form,setForm]=useState<Omit<Member,'id'|'crew_id'>>(member??blank(settings.data?.default_cwd??''))
  useEffect(()=>{if(!member&&settings.data&&!form.cwd)setForm(f=>({...f,cwd:settings.data!.default_cwd}))},[settings.data,member,form.cwd])
  const catalogCwd=useDebouncedValue(form.cwd)
  const catalog=useQuery({queryKey:['capabilities',form.device_id,catalogCwd],queryFn:()=>endpoints.capabilities(form.device_id,catalogCwd),enabled:!!form.device_id&&!!catalogCwd&&devices.data?.find(d=>d.id===form.device_id)?.status!=='offline',retry:0})
  const set=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>setForm(f=>({...f,[key]:value}))
  const providers=catalog.data?.models.providers??[];const selected=providers.find(p=>p.id===form.provider)
  return <div className="stack"><div className="form-grid"><Field label="Name"><Input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Backend"/></Field><Field label="Role"><Input value={form.role} onChange={e=>set('role',e.target.value)} placeholder="Implementation and review"/></Field><Field label="Device"><Select value={form.device_id} onChange={v=>{setForm(f=>({...f,device_id:v,provider:null,model:null,skills:[],mcp_servers:[]}))}}>{devices.data?.map(d=><option key={d.id} value={d.id}>{d.name} · {d.status}</option>)}</Select></Field><Field label="Working directory"><Input value={form.cwd} onChange={e=>set('cwd',e.target.value)} placeholder="Absolute path on selected device"/></Field></div>
    {catalog.error&&<div className="text-xs text-danger">AX capability lookup failed: {String(catalog.error)}</div>}
    <div className="form-grid"><Field label="Provider"><Select value={form.provider??''} onChange={v=>{set('provider',v||null);set('model',null)}} disabled={!catalog.data}><option value="">AX default</option>{providers.map(p=><option key={p.id} value={p.id}>{p.id}</option>)}</Select></Field><Field label="Model"><Select value={form.model??''} onChange={v=>set('model',v||null)} disabled={!catalog.data||!form.provider}><option value="">AX default</option>{selected?.models.map(m=><option key={m.id} value={m.id}>{m.display_name||m.id}</option>)}</Select></Field></div>
    <div className="form-grid"><Field label="Skills" hint="Installed skills on this AX device"><div className="max-h-36 overflow-y-auto border border-border p-2">{catalog.data?.skills.skills.map(s=><label className="flex gap-2 py-1 text-xs text-foreground" key={s.name}><input type="checkbox" checked={form.skills.includes(s.name)} onChange={e=>set('skills',e.target.checked?[...form.skills,s.name]:form.skills.filter(n=>n!==s.name))}/><span>{s.name}<span className="ml-1 text-muted">{s.description}</span></span></label>)}{!catalog.data?.skills.skills.length&&<span className="text-xs text-muted">No skills reported</span>}</div></Field><Field label="MCP servers" hint="Names from this device's AX MCP config"><div className="max-h-36 overflow-y-auto border border-border p-2">{catalog.data?.mcp.servers.filter(s=>s.enabled).map(s=><label className="flex gap-2 py-1 text-xs text-foreground" key={s.name}><input type="checkbox" checked={form.mcp_servers.includes(s.name)} onChange={e=>set('mcp_servers',e.target.checked?[...form.mcp_servers,s.name]:form.mcp_servers.filter(n=>n!==s.name))}/>{s.name}</label>)}{!catalog.data?.mcp.servers.length&&<span className="text-xs text-muted">No MCP servers reported</span>}</div></Field></div>
    <div className="form-grid"><Field label="Permission profile"><Select value={form.permission_profile} onChange={v=>set('permission_profile',v as Member['permission_profile'])}><option value="ask">Ask</option><option value="allow">Allow</option><option value="deny">Deny</option></Select></Field><Field label="Maximum concurrency"><Input type="number" min={1} value={form.max_concurrency} onChange={e=>set('max_concurrency',Number(e.target.value))}/></Field></div>
    <div className="flex justify-end"><Action disabled={!form.name.trim()||!form.cwd.trim()||form.cwd!==catalogCwd||!Number.isInteger(form.max_concurrency)||form.max_concurrency<1||!catalog.data} run={async()=>{await api(member?`/api/crews/${crewId}/members/${member.id}`:`/api/crews/${crewId}/members`,member?'PUT':'POST',form);close()}}>{member?'Save member':'Add member'}</Action></div>
  </div>
}
export function CrewDetail(){const {id=''}=useParams(),crews=useCrews(),members=useMembers(id),tasks=useTasks(),devices=useDevices(),[editing,setEditing]=useState<Member|'new'|null>(null),crew=crews.data?.find(c=>c.id===id)
  if(!crew)return <div className="page"><Empty title={crews.isPending?'正在加载团队…':crews.isError?'无法加载团队':'团队不存在'}/></div>
  return <div className="page"><PageHead eyebrow="Crew workspace" title={crew.name} description={`${members.data?.length??0} agents · ${(tasks.data??[]).filter(t=>t.crew_id===id).length} tasks`} actions={<><Button variant="secondary" onClick={()=>setEditing('new')}><Plus size={14}/> Add Agent</Button><Link to={`/tasks?crew=${id}`}><Button>Open Task DAG</Button></Link></>}/>
    <h2 className="section-title">Agents</h2><div className="panel">{members.data?.map(m=>{const active=tasks.data?.find(t=>t.assigned_member===m.id&&['running','waiting_permission','ready'].includes(t.status)),device=devices.data?.find(d=>d.id===m.device_id);return <div className="row" key={m.id}><Link to={`/crews/${id}/members/${m.id}`} className="flex min-w-0 flex-1 items-center gap-4 no-underline text-foreground"><Status value={active?.status??device?.status??'offline'}/><div className="min-w-0"><div className="row-title">{m.name}<span className="ml-2 font-normal text-muted">{m.role}</span></div><div className="row-sub">{device?.name??m.device_id} · {m.provider??'AX default'} / {m.model??'default'}{active&&` · ${active.title}`}</div></div></Link><Button variant="ghost" size="icon" onClick={()=>setEditing(m)} aria-label={`Edit ${m.name}`}><Settings2 size={15}/></Button><Link to={`/crews/${id}/members/${m.id}`} className="link"><ArrowUpRight size={15}/></Link></div>})}{!members.data?.length&&<Empty title="No agents in this Crew" description="Members use real AX runtimes on selected devices." action={<Button onClick={()=>setEditing('new')}>Add Agent</Button>}/>}</div>
    <h2 className="section-title">Recent tasks</h2><div className="panel">{tasks.data?.filter(t=>t.crew_id===id).slice(-12).reverse().map(t=><Link key={t.id} to={`/tasks/${t.id}`} className="row justify-between no-underline text-foreground"><span>{t.title}</span><Status value={t.status}/></Link>)}{!tasks.data?.some(t=>t.crew_id===id)&&<Empty title="No tasks yet"/>}</div>
    <Dialog open={!!editing} onOpenChange={v=>!v&&setEditing(null)} title={editing==='new'?'Add Agent':'Edit Agent'} wide>{editing&&<MemberEditor key={editing==='new'?'new':editing.id} crewId={id} member={editing==='new'?undefined:editing} close={()=>setEditing(null)}/>}</Dialog>
  </div>
}
export function MemberWorkspace(){const {id='',memberId=''}=useParams(),members=useMembers(id),tasks=useTasks(),navigate=useNavigate(),member=members.data?.find(m=>m.id===memberId),related=(tasks.data??[]).filter(t=>t.assigned_member===memberId).reverse(),[selected,setSelected]=useState('')
  useEffect(()=>{if(!related.some(task=>task.id===selected))setSelected(related[0]?.id??'')},[selected,related])
  if(!member)return <div className="page"><Empty title={members.isPending?'正在加载成员…':members.isError?'无法加载成员':'成员不存在'}/></div>
  return <div className="page"><PageHead eyebrow="Agent workspace" title={member.name} description={`${member.role} · ${member.device_id} · ${member.model??'AX default'}`} actions={<Button variant="secondary" onClick={()=>navigate(`/crews/${id}`)}>Crew overview</Button>}/><div className="grid min-h-[70vh] grid-cols-[220px_1fr] gap-5"><aside className="panel"><div className="panel-header">Executions</div>{related.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={`row w-full text-left ${selected===t.id?'bg-hover':''}`}><div className="min-w-0 flex-1"><div className="row-title truncate">{t.title}</div><Status value={t.status}/></div></button>)}{!related.length&&<Empty title="No executions yet"/>}</aside><section className="panel min-w-0">{selected?<SessionThread taskId={selected}/>:<Empty title="No AX Session" description="Assign a task to this member to open a persistent execution workspace."/>}</section></div></div>
}
