import { useT } from '../lib/i18n'
import { useRef, useState, type ReactNode } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { LoaderCircle } from 'lucide-react'
import { Button } from './ui/button'
import { cn } from '../lib/utils'

export function PageHead({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="flex items-center gap-2">{actions}</div></header>}
export function Empty({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="empty"><div className="font-medium">{title}</div>{description&&<p className="mt-1 text-sm text-muted">{description}</p>}{action&&<div className="mt-4">{action}</div>}</div>}
export function Status({value}:{value:string}){const t=useT();return <span className="inline-flex items-center gap-2 text-xs text-muted"><span className={cn('h-1.5 w-1.5 rounded-full',value==='online'||value==='completed'||value==='Connected'?'bg-success':value==='running'||value==='busy'||value==='waiting_permission'?'bg-warning':value==='failed'||value==='error'||value==='offline'?'bg-danger':'bg-muted')}/>{t('status.'+value)===('status.'+value)?value.replaceAll('_',' '):t('status.'+value)}</span>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="block text-xs text-muted"><span className="mb-1.5 block font-medium text-foreground">{label}</span>{children}{hint&&<span className="mt-1 block">{hint}</span>}</label>}
export function Select({value,onChange,children,disabled}:{value:string;onChange:(value:string)=>void;children:ReactNode;disabled?:boolean}){return <select value={value} onChange={event=>onChange(event.target.value)} disabled={disabled} className="ax-field h-8 w-full border border-border bg-surface px-2 text-[13px] text-foreground disabled:opacity-50">{children}</select>}
export function Action({children,run,variant='secondary',disabled=false}:{children:ReactNode;run:()=>Promise<unknown>;variant?:'default'|'secondary'|'ghost'|'danger';disabled?:boolean}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const query=useQueryClient(),lock=useRef(false);return <span className="inline-flex flex-col items-start"><Button variant={variant} disabled={disabled||busy} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await run();await query.invalidateQueries()}catch(e){setError(String(e))}finally{lock.current=false;setBusy(false)}}}>{busy&&<LoaderCircle size={13} className="animate-spin"/>}{children}</Button>{error&&<small className="max-w-xs text-danger">{error}</small>}</span>}
